### ISSUE TITLE
Validation in Controller

### ISSUE THREAD

**Issue by lucianobosco** [Nelson-Dominici/Slimgry#1]
Hi! This looks promising. Do you plan to make it available to work in controllers like Laravel validator?
In terms of DDD, I think having validation in Presentation layer is more accurate than having them in routes.
I sthere any workaround to make it work in controller right now?

**Comment by Nelson-Dominici** [comment]
For now, making it work in controllers is not my focus, besides, I prefer to keep the validations in the routes, but depending on the wishes of the people who use the lib, I can add it.

**Comment by khurshid444** [comment]
i also think the laravel approach on validation in the controller makes sense, as the routes are kept clear and the validation part can be done in controller only. when are u planning to do ?
